config/routes.rb
Rails.application.routes.draw do
  root 'home#input'
  post '/result', to: 'home#result'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home_result.rb
class HomeResult
  include ActiveModel::Model
  include HomeHelper
  include ActiveModel::Validations
  attr_accessor :arr, :num
  validate :check_input
  validate :result
  validates :arr, :num, presence: { message: "can't be empty" }
  validates :arr, format: { with: /^\s*(\d+\s*)*$/, multiline: true, message: 'must contain only positive numbers' }

  def result
    arr = init
    @result_arr, @max_i = HomeHelper.solve(arr)
    if @result_arr.length.zero?
      errors.add(:segment, "count is equal to zero")
    end
    [@result_arr, @max_i]
  end

  def check_input
    if num != arr&.split&.length&.to_s
      errors.add(:number, "of elements in array are not matching with first field")
    end
  end

  def init
    arr = '1 2 3 4 5' if arr.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# controller class
class HomeController < ApplicationController
  def input; end

  def result
    @home = HomeResult.new(home_params)
  end

  private

  def home_params
    params.permit(:arr, :num)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# help module
module HomeHelper
  def self.solve(arr)
    temp_count = 0
    max_count = 0
    result_arr = []
    max_i = 0
    arr = arr.split.map(&:to_i)
    i = 0
    arr.each do |el|
      temp_count, i = HomeHelper.sqrt(el, i, result_arr, temp_count)
      if temp_count > max_count
        max_count = temp_count
        max_i = i
      end
    end
    [result_arr, max_i]
  end

  def self.sqrt(elem, ind, result_arr, temp_count)
    if Math.sqrt(elem).to_s.match(/^\d*.0$/)
      result_arr[ind] = if temp_count.zero?
                          elem.to_s
                        else
                          "#{result_arr[ind]} #{elem}"
                        end
      [temp_count + 1, ind]
    else
      [0, ind + 1]
    end
  end
end

app/views/home/_footer.html.erb
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Company, Inc</p>
  </footer>

app/views/home/_header.html.erb
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><p2><%= link_to 'FlyRexy', root_path, class: 'nav-link px-2 text-white' %></p2></li>
<!--        <li><%#= link_to 'About us', home_result_path, class: "nav-link px-2 text-white" %></li>-->
<!--        <li><%#= link_to 'Movies', movies_path, class: "nav-link px-2 text-white" %></li>-->
      </ul>

    </div>
  </div>
</header>

app/views/home/_result_table.html.erb
<% if @home.valid? %>
  <h2>Самый длинный отрезок: <%= @home.result[0][@home.result[1]] %></h2>
  <h2>Количество отрезков: <%= @home.result[0].compact.length %></h2>
  <h1>Все отрезки:</h1>
  <table class = "table table-dark" style = "width: 50%">
    <tr>
      <td style = "width: 50px">№ отрезка</td>
      <td style = "width: 80%">Отрезок</td>
    </tr>
    <% i = 0 %>
    <% while i < @home.result[0].compact.length do %>
      <tr>
        <td><%= i + 1 %></td>
        <td><%= @home.result[0].compact[i] %></td>
      </tr>
      <% i += 1 %>
    <% end %>
  </table>
  <% else %>
  <% @home.errors.each do |error| %>
    <ul class="list-group">
      <li class="list-group-item"><%= error.full_message %></li>
    </ul>
  <% end %>
<% end %>

app/views/home/input.html.erb
<div class = 'container'>
  <div class = "row">
    <div class = 'col-3'>
      <br>
      <%= form_with url: result_path do |form|%>
        <%= form.label("Input number of elements in array")%>
        <br>
        <%= form.number_field :num, in: 1..300, step: 1, class: "form-control form-control-dark text-bg-dark" %>
        <br>
        <%= form.label("Input elements of array")%>
        <br>
        <%= form.text_area :arr, size: "15x1", class: "form-control form-control-dark text-bg-dark"%>
        <br>
        <%= form.button "Get result", class: "glow-on-hover", id: "my_button"%>
      <% end %>
    </div>
    <br>
    <br>
    <div class = "col-6">
      <div style = "padding-top: 15px; padding-left: 50px" id = "result_area">

      </div>
    </div>
  </div>
</div>

app/views/home/result.turbo_stream.erb
<%= turbo_stream.update 'result_area', partial: 'result_table' %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>myApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
<%= render 'home/header' %>
<div class = "container">
  <%= yield %>
</div>
<%= render 'home/footer' %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>